const ManageActionTypes = {
    GET_LIST_START: 'GET_LIST_START',
    GET_LIST_SUCCESS: 'GET_LIST_SUCCESS',
    GET_LIST_FAILURE: 'GET_LIST_FAILURE',
    GET_INDIVIDUAL_START: 'GET_INDIVIDUAL_START',
    GET_INDIVIDUAL_SUCCESS: 'GET_INDIVIDUAL_SUCCESS',
    GET_INDIVIDUAL_FAILURE: 'GET_INDIVIDUAL_FAILURE'
}
export default ManageActionTypes