const ManageActionTypes = {
    GET_LIST_START: 'GET_LIST_START',
    GET_LIST_SUCCESS: 'GET_LIST_SUCCESS',
    GET_LIST_FAILURE: 'GET_LIST_FAILURE',
    GET_INDIVIDUAL_START: 'GET_INDIVIDUAL_START',
    GET_INDIVIDUAL_SUCCESS: 'GET_INDIVIDUAL_SUCCESS',
    GET_INDIVIDUAL_FAILURE: 'GET_INDIVIDUAL_FAILURE',
    UPDATE_INDIVIDUAL_START: 'UPDATE_INDIVIDUAL_START',
    UPDATE_INDIVIDUAL_SUCCESS: 'UPDATE_INDIVIDUAL_SUCCESS',
    UPDATE_INDIVIDUAL_FAILURE: 'UPDATE_INDIVIDUAL_FAILURE',
    CREATE_INDIVIDUAL_START: 'CREATE_INDIVIDUAL_START',
    CREATE_INDIVIDUAL_SUCCESS: 'CREATE_INDIVIDUAL_SUCCESS',
    CREATE_INDIVIDUAL_FAILURE: 'CREATE_INDIVIDUAL_FAILURE',
    DELETE_INDIVIDUAL_START: 'DELETE_INDIVIDUAL_START',
    DELETE_INDIVIDUAL_SUCCESS: 'DELETE_INDIVIDUAL_SUCCESS',
    DELETE_INDIVIDUAL_FAILURE: 'DELETE_INDIVIDUAL_FAILURE'
}
export default ManageActionTypes