const EmployeesActionTypes = {
    GET_EMPLOYEES_START: 'GET_EMPLOYEES_START',
    GET_EMPLOYEES_SUCCESS: 'GET_EMPLOYEES_SUCCESS',
    GET_EMPLOYEES_FAILURE: 'GET_EMPLOYEES_FAILURE',
    GET_EMPLOYEE_START: 'GET_EMPLOYEE_START',
    GET_EMPLOYEE_SUCCESS: 'GET_EMPLOYEE_SUCCESS',
    GET_EMPLOYEE_FAILURE: 'GET_EMPLOYEE_FAILURE'
}
export default EmployeesActionTypes