const AuthActionTypes = {
    LOGIN_START : 'LOGIN_START',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    SIGN_OUT_START : 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS : 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE : 'SIGN_OUT_FAILURE',
    SIGN_UP_START : 'SIGN_UP_START',
    SIGN_UP_SUCCESS : 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE : 'SIGN_UP_FAILURE',
}
export default AuthActionTypes